/**
 * Represents a token generated by the text analysis pipeline.
 */
export interface Token {
  /** The normalized, stemmed term string */
  term: string;
  /** Sequential token position index (0-indexed) within the document stream */
  position: number;
  /** Byte/character start offset in the original document string */
  startOffset: number;
  /** Byte/character end offset in the original document string */
  endOffset: number;
}

/**
 * Configuration options for the text analyzer pipeline.
 */
export interface AnalyzerOptions {
  /** Whether to convert tokens to lowercase (default: true) */
  lowercase?: boolean;
  /** Whether to strip HTML tags prior to tokenization (default: false) */
  stripHtml?: boolean;
  /** Whether to normalize Unicode diacritics via NFKD (default: true) */
  stripDiacritics?: boolean;
  /**
   * Stopword filtering configuration:
   * - true: use standard English stopwords (~170 words)
   * - false: do not filter stopwords
   * - Array or Set of strings: custom stopword dictionary
   */
  stopWords?: boolean | string[] | Set<string>;
  /** Whether to apply the Porter Stemmer algorithm (default: true) */
  stemming?: boolean;
  /** Minimum character length for tokens to be indexed (default: 1) */
  minTokenLength?: number;
  /** Maximum character length for tokens to be indexed (default: 64) */
  maxTokenLength?: number;
}
